<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit97f015dbb7b11fdd5ed6bcaf516f6e53
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('CheckoutWC\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \CheckoutWC\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit97f015dbb7b11fdd5ed6bcaf516f6e53', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \CheckoutWC\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit97f015dbb7b11fdd5ed6bcaf516f6e53', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\CheckoutWC\Composer\Autoload\ComposerStaticInit97f015dbb7b11fdd5ed6bcaf516f6e53::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \CheckoutWC\Composer\Autoload\ComposerStaticInit97f015dbb7b11fdd5ed6bcaf516f6e53::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
